services:
    - type: worker
      name: discord-music-bot
      env: node
      plan: free
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_VERSION
            value: 24.6.0
